version: '3'

services:
  serve-docker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - TZ=UTC
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /Users/lucas.loeffel/serve:/home/serve